- name: Check if bootstrap is needed
  raw: stat $HOME/.bootstrapped
  register: need_bootstrap
  ignore_errors: True

- name: Run bootstrap.sh
  script: bootstrap.sh
  when: need_bootstrap is failed

- name: Check if we need to install pip
  shell: "{{ansible_python_interpreter}} -m pip --version"
  register: need_pip
  ignore_errors: True
  changed_when: false

- name: Copy get-pip.py
  get_url: url=https://bootstrap.pypa.io/2.7/get-pip.py dest=~/get-pip.py mode=0644
  when: need_pip is failed

- name: Install pip
  shell: "{{ansible_python_interpreter}} ~/get-pip.py"
  when: need_pip is failed

- name: Remove get-pip.py
  file: path=~/get-pip.py state=absent
  when: need_pip is failed

- name: Install pip launcher
  copy: src=runner dest=~/bin/pip mode=0755
  when: need_pip is failed
